FROM debian:8.2
MAINTAINER Daniel Ritchie

ENV http_proxy 
ENV https_proxy 
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
 && apt-get upgrade -qy \
 && apt-get install -qy cntlm redsocks

COPY conf/cntlm.conf /etc/cntlm.conf
COPY conf/redsocks.conf /etc/redsocks.conf
COPY etc/startup.sh /startup.sh

RUN chmod 600 /etc/cntlm.conf
RUN chmod +x startup.sh

EXPOSE 3128
EXPOSE 3129

CMD [ "./startup.sh" ]